//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSTOX.DataPusher.BOService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BOFile", Namespace="http://schemas.datacontract.org/2004/07/NSTOX.WebService.Model")]
    [System.SerializableAttribute()]
    public partial class BOFile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FileContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FileDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NSTOX.DataPusher.BOService.BOFileType FileTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RetailerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RetailerNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] FileContent {
            get {
                return this.FileContentField;
            }
            set {
                if ((object.ReferenceEquals(this.FileContentField, value) != true)) {
                    this.FileContentField = value;
                    this.RaisePropertyChanged("FileContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FileDate {
            get {
                return this.FileDateField;
            }
            set {
                if ((this.FileDateField.Equals(value) != true)) {
                    this.FileDateField = value;
                    this.RaisePropertyChanged("FileDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NSTOX.DataPusher.BOService.BOFileType FileType {
            get {
                return this.FileTypeField;
            }
            set {
                if ((this.FileTypeField.Equals(value) != true)) {
                    this.FileTypeField = value;
                    this.RaisePropertyChanged("FileType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RetailerId {
            get {
                return this.RetailerIdField;
            }
            set {
                if ((this.RetailerIdField.Equals(value) != true)) {
                    this.RetailerIdField = value;
                    this.RaisePropertyChanged("RetailerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RetailerName {
            get {
                return this.RetailerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RetailerNameField, value) != true)) {
                    this.RetailerNameField = value;
                    this.RaisePropertyChanged("RetailerName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BOFileType", Namespace="http://schemas.datacontract.org/2004/07/NSTOX.BODataProcessor.Model")]
    public enum BOFileType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Items = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Departments = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Transactions = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BOService.IBOService")]
    public interface IBOService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBOService/PushBOFile", ReplyAction="http://tempuri.org/IBOService/PushBOFileResponse")]
        bool PushBOFile(NSTOX.DataPusher.BOService.BOFile file);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBOService/ProcessBOFilesForRetailer", ReplyAction="http://tempuri.org/IBOService/ProcessBOFilesForRetailerResponse")]
        bool ProcessBOFilesForRetailer(int retailerId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBOServiceChannel : NSTOX.DataPusher.BOService.IBOService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BOServiceClient : System.ServiceModel.ClientBase<NSTOX.DataPusher.BOService.IBOService>, NSTOX.DataPusher.BOService.IBOService {
        
        public BOServiceClient() {
        }
        
        public BOServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BOServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BOServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BOServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool PushBOFile(NSTOX.DataPusher.BOService.BOFile file) {
            return base.Channel.PushBOFile(file);
        }
        
        public bool ProcessBOFilesForRetailer(int retailerId) {
            return base.Channel.ProcessBOFilesForRetailer(retailerId);
        }
    }
}
